// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8yQboOEmjRGHVzz0RCjO9eLSjIR6SyWM',
    appId: '1:249841062966:web:24ab69f773dbbe524cb497',
    messagingSenderId: '249841062966',
    projectId: 'appcolegio-3162a',
    authDomain: 'appcolegio-3162a.firebaseapp.com',
    storageBucket: 'appcolegio-3162a.firebasestorage.app',
    measurementId: 'G-TLCY8XT6SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBzMPD4oLmCzlV8HkBKD6D2ijCxfNYYMo',
    appId: '1:249841062966:android:0f34bbc38e3144944cb497',
    messagingSenderId: '249841062966',
    projectId: 'appcolegio-3162a',
    storageBucket: 'appcolegio-3162a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvtS9g7QqB_j3FqE6CFpYzkYNxzG5fH0',
    appId: '1:249841062966:ios:97f22cb2932ead834cb497',
    messagingSenderId: '249841062966',
    projectId: 'appcolegio-3162a',
    storageBucket: 'appcolegio-3162a.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );
}
